# Usar a imagem oficial do MongoDB
FROM mongo:latest

# Criar o diretório /app dentro do contêiner (opcional, se ele não existir)
RUN mkdir /app

# Copiar tudo da pasta "Programas" para o diretório "/app"
COPY Programas /app

# Definir o diretório app como diretório de trabalho
WORKDIR /app

# Expor a porta 27017
EXPOSE 27017    

# Comando para iniciar o MongoDB
CMD ["mongod"]
